In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

In [ ]:
FINESS = pd.read_excel("finess.xlsx")
FINESS = FINESS.drop(FINESS.columns[[1,2,4]],axis=1)
FINESS = FINESS.rename(columns={"FINESS":"FI","Statut Juridique":"Statut"})

array(['Public', 'Privé non lucratif', 'Privé lucratif'], dtype=object)

In [ ]:
SYGEN2022 = pd.read_csv("SAE/2022/SYGEN_2022r.csv", sep=";", encoding="latin-1")
Data = SYGEN2022

Urg2022 = pd.read_csv("SAE/2022/URGENCES2_2022r.csv", sep=";", encoding="latin-1")
Urg2022 = Urg2022[['FI','PASSU']]
Data = Data.merge(Urg2022, on="FI", how="left")

In [ ]:
filtre = pd.read_csv("SAE/2022/FILTRE_2022.csv")

In [3]:
Data.head()

,FI,FI_EJ,AN,LIT_MED,LIT_CHI,LIT_OBS,LIT_MCO,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,...,NB_IRM,ACT_IRM,NB_CAM,ACT_CAM,NB_TOMO,ACT_TOMO,SAL_INTERV,POST_REVEIL,BOR,PASSU
0,010000024,010780054,2022,270.0,68.0,47.0,385.0,14972.0,7260.0,3474.0,...,3.0,0.0,NaN,NaN,NaN,NaN,13.0,19.0,SYGEN,42384.0
1,010000032,010780062,2022,66.0,17.0,8.0,91.0,4020.0,970.0,501.0,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,6.0,SYGEN,16727.0
2,010000065,010780096,2022,59.0,NaN,NaN,59.0,1669.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN,NaN
3,010000081,010780112,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN,NaN
4,010000099,010780120,2022,10.0,NaN,NaN,10.0,170.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SYGEN,NaN

In [4]:
Data['MED'] = Data['EFFSAL_TOT'] + Data['EFFLIB_TOT']
Data['ADMIN'] = Data['ETP_DIR'] + Data['ETP_AUTADM']
Data["SEANCES"] = Data['SEAN_HEMO_CENTRE'] + Data['SEAN_CHIMIO'] + Data['SEAN_RADIO']
Data['PSY'] = Data['SEJ_HTP_TOT'] + Data['VEN_HDJ_TOT'] + Data['VEN_HDN_TOT']

In [ ]:
Data["lURG"] = np.where(Data["PASSU"] > 0, np.log(Data["PASSU"]), 0)
Data["lMCO_AMB"] = np.where(Data["SEJHP_MCO"] > 0, np.log(Data["SEJHP_MCO"]), 0)
Data["lMCO_COMP"] = np.where(Data["SEJHC_MCO"] > 0, np.log(Data["SEJHC_MCO"]), 0)
Data["lPSY"] = np.where(Data["PSY"] > 0, np.log(Data["PSY"]), 0)
Data["lSSR"] = np.where(Data["SEJHC_SSR"] > 0, np.log(Data["SEJHC_SSR"]), 0)
Data["lSEANCES"] = np.where(Data["SEANCES"] > 0, np.log(Data["SEANCES"]), 0)

Data["lMED"] = np.where(Data["MED"] > 0, np.log(Data["MED"]), 0)
Data["lIDE"] = np.where(Data["EFF_INFSANSSPE"] > 0, np.log(Data["EFF_INFSANSSPE"]), 0)
Data["lAID"] = np.where(Data["EFF_AID"] > 0, np.log(Data["EFF_AID"]), 0)
Data["lADMIN"] = np.where(Data["ADMIN"] > 0, np.log(Data["ADMIN"]), 0)

c:\Users\roman\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
c:\Users\roman\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\core\arraylike.py:399: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [9]:
Data.head()

,FI,FI_EJ,AN,LIT_MED,LIT_CHI,LIT_OBS,LIT_MCO,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,...,PSY,lURG,lMCO_AMB,lPSY,lSSR,lSEANCES,lMED,lIDE,lAID,lADMIN
0,010000024,010780054,2022,270.0,68.0,47.0,385.0,14972.0,7260.0,3474.0,...,NaN,10.654526,6.739337,0.0,0.000000,10.545762,5.384495,6.068426,5.905362,5.518416
1,010000032,010780062,2022,66.0,17.0,8.0,91.0,4020.0,970.0,501.0,...,NaN,9.724779,7.440147,0.0,6.142037,0.000000,0.000000,4.499810,4.356709,3.968214
2,010000065,010780096,2022,59.0,NaN,NaN,59.0,1669.0,0.0,0.0,...,NaN,0.000000,0.000000,0.0,6.545350,0.000000,0.000000,4.174387,4.595120,3.070840
3,010000081,010780112,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000,0.000000,0.0,4.795791,0.000000,0.000000,2.772589,3.610918,1.451614
4,010000099,010780120,2022,10.0,NaN,NaN,10.0,170.0,0.0,0.0,...,NaN,0.000000,0.000000,0.0,5.564520,0.000000,1.945910,2.197225,3.135494,1.366092

In [12]:
hd = pd.read_csv("Hospidiag/hd2022.csv", sep=";", decimal = ",", encoding="latin-1")
hd = hd.rename(columns={"finess":"FI_EJ"})
Data = Data.merge(hd, how="left", on="FI_EJ")
Data.head()

,FI,FI_EJ,AN,LIT_MED,LIT_CHI,LIT_OBS,LIT_MCO,SEJHC_MED,SEJHC_CHI,SEJHC_OBS,...,RH1,RH2,RH3,RH4,RH5,RH6,RH7,RH8,RH9,RH10
0,010000024,010780054,2022,270.0,68.0,47.0,385.0,14972.0,7260.0,3474.0,...,44.0,13193.4,79427.4,26.3,1.8,5.4,NaN,"9,4",12,NaN
1,010000032,010780062,2022,66.0,17.0,8.0,91.0,4020.0,970.0,501.0,...,31.0,32052.5,68260.5,21.6,NaN,8.1,NaN,"8,6","11,2",NaN
2,010000065,010780096,2022,59.0,NaN,NaN,59.0,1669.0,0.0,0.0,...,NaN,NaN,NaN,19.7,NaN,NaN,NaN,NaN,NaN,NaN
3,010000081,010780112,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,010000099,010780120,2022,10.0,NaN,NaN,10.0,170.0,0.0,0.0,...,NaN,NaN,NaN,22.3,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
outputs = ["lURG", "lMCO_AMB", "lMCO_COMP", "lSSR", "lPSY","lSEANCES"]
model_med = sm.OLS('lMED ~ outputs + C(Statut) + A14', data=Data).fit(cov_type="HC1")
#ajouter indic  HEB_MED, HEB_CHIR,HEB_PERINAT,HEB_PSY,HEB_SSR du fichier filtre (ils sont déjà en indic)